### ISSUE TITLE
I can't access my local path

### ISSUE THREAD

**Issue by ghanIn-dev** [geerlingguy/ansible-role-awx#15]
https://github.com/ansible/awx/issues/857

same issue that link

but i don't know how can i fix it 

please help me

**Comment by vab2048** [comment]
You can use my fork available here:

https://github.com/vab2048/ansible-role-awx

This should solve the problem for you. It defaults to using "/var/lib/awx/projects/" as the project data dir

**Comment by ghanIn-dev** [comment]
@vab2048  
First I'm really thank you for your reply
and i have question

now i clone your git repo but i can't install awx
i  can't play playbook

this is my role folder list
![image](https://user-images.githubusercontent.com/15894443/39900739-deaf7cda-54fe-11e8-9204-2ab300a83369.png)

and this is my playbook
![image](https://user-images.githubusercontent.com/15894443/39900755-fc2172aa-54fe-11e8-8ee6-894e4f38a11c.png)

and this is my error
![image](https://user-images.githubusercontent.com/15894443/39900780-33766ea4-54ff-11e8-84da-73c8e8014a1e.png)

what shoul i do?

**Comment by ghanIn-dev** [comment]
@vab2048

i installed it to change my folder name (ansible-role-awx -> geerlingguy.awx  / sorry about stupid question im beginner)
but its not working to me
i have site.yml in local /var/lib/awx/projects but awx can't load this 

is anythind i have to do someting?

**Comment by htouloupas** [comment]
When this error occurs it means that ansible can't find the specific role in the path it checks. You need to go to ansible.cfg or make such a file and add to the roles_path variable the path of the folder where the role is downloaded. Please read the docs.
