### ISSUE TITLE
Blank login page after install of AWX - no /var/lib/awx/public/static directory

### ISSUE THREAD

**Issue by leedt03** [geerlingguy/ansible-role-awx#18]
Hi Jeff - firstly thanks for creating a role that installs AWX. I'm not sure if I should be asking here or on the AWX group....

I installed AWX today via your role - it installed without issues. When I browsed to the webpage AWX had an upgrade message on it, after a period of time it just went to a blank white screen. After a number of reboots etc I can only launch to a blank white screen which has AWX in the address bar.

AWX is running on an Ubuntu 17.10 box. Let me know what other info I can provide to assist.....

Update - I can access http://awx/api and then login, just can't access http://awx

I've just posted this on the AWX project support forum as I suspect this is an issue on the AWX side (or my server itself?), not an issue with the role. 

Thanks in advance!

**Comment by leedt03** [comment]
I've built a new Ansible box  - deployed AWX via the role again still with the same issue.

After checking the docker logs for the web container it logs about copying 349 static images to a path that doesn't even exist.

/var/lib/awx/public/static/

I have no awx folder here - any ideas on why?

_"349 static files copied to '/var/lib/awx/public/static'."_

**Comment by leedt03** [comment]
Sorry - was going down wrong path with this (new to Docker!) - path did exist but only visible within container. Issue is Internet Explorer 11 (after installing Chrome I can see login page) - weird as the API login page works without issues with IE11.

**Comment by geerlingguy** [comment]
@javacat33 - No worries! I would imagine it's some frontend JS bug with IE11... not sure if the AWX/Tower team at Ansible supports IE11 (probably just Edge).

**Comment by tedfernandess** [comment]
How can I get it working with IE 11?
