### ISSUE TITLE
create_host_config() got an unexpected keyword argument 'init'

### ISSUE THREAD

**Issue by Publish-Interactive** [geerlingguy/ansible-role-awx#21]
Perhaps not directly the fault of this role, but it currently fails for me on step 'Run the AWX installation playbook.' with error 'create_host_config() got an unexpected keyword argument 'init' on Ubuntu 16.04.

Looks like an issue with a combination of Ansible and Docker (see issues [42162](https://github.com/ansible/ansible/issues/42162) and [2041](https://github.com/ansible/awx/issues/2041)).

I managed to get past by downgrading Ansible to v2.5.5 (the geerlingguy.ansible role currently installs 2.6.1).

Others with similar issues seemed to get by with switching between docker/docker-py/docker-ce but I didn't).

Hoped adding this issue here might help others struggling with this popular role.

**Comment by cryptomatt** [comment]
Thanks for your solution, had the same problem, downgrading explicitly worked for me.
