### ISSUE TITLE
Error during installation - CentOS 7

### ISSUE THREAD

**Issue by squalo-villa** [geerlingguy/ansible-role-awx#31]
Hi all,

I'm trying to install AWX using this template, however, after fixing the dependency issue where it lacks docker-compose (added during pip install), I've got this blocker now:

`"TASK [local_docker : Activate AWX Web Container] *******************************", "fatal: [localhost]: FAILED! => {\"changed\": false, \"msg\": \"Non-string value found for env option. Ambiguous env options must be wrapped in quotes to avoid them being interpreted. Key: DATABASE_PORT\"}"`

INFO:
`
docker-compose version 1.25.4, build 8d51620a
npm --version 3.10.10
Docker version 19.03.8, build afacb8b
pip 8.1.2 from /usr/lib/python2.7/site-packages (python 2.7)

Machine:
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
`

Thanks

**Comment by mkesper** [comment]
I'd interpret the message so that you have to write the database port "number" as e.g. "8080", not 8080.
