### ISSUE TITLE
podman & buildah errors on redhat systems

### ISSUE THREAD

**Issue by Gr4cchus** [geerlingguy/ansible-role-awx#37]
An error of this sort will pop up on rhel8/centos8/centosstream because podman and buildah are installed and try to replace docker. Making sure those packages are uninstalled on a server will prevent this from happening:  
 ```
TASK [geerlingguy.docker : Ensure containerd.io is installed.] ************************
fatal: [192.168.1.1]: FAILED! => {"changed": false, "failures": [], "msg": "Depsolve Error occured: \n Problem: problem with installed package buildah-1.15.1-2.module+el8.3.0+8221+97165c3f.x86_64\n  - package buildah-1.15.1-2.module+el8.3.0+8221+97165c3f.x86_64 requires runc >= 1.0.0-26, but none of the providers can be installed\n  - package buildah-1.5-3.gite94b4f9.module+el8+2769+577ad176.x86_64 requires runc >= 1.0.0-26, but none of the providers can be installed\n  - package buildah-1.5-3.gite94b4f9.module+el8.0.0+2958+4e823551.x86_64 requires runc >= 1.0.0-26, but none of the providers can be installed\n  - package buildah-1.5-3.gite94b4f9.module+el8.0.0+4017+bbba319f.x86_64 requires runc >= 1.0.0-26, but none of the providers can be installed\n  - package buildah-1.5-3.gite94b4f9.module+el8.0.0.z+3525+56c076c3.x86_64 requires runc >= 1.0.0-26, but none of the providers can be installed\n  - package buildah-1.9.0-5.module+el8.1.0+4240+893c1ab8.x86_64 requires runc >= 1.0.0-26, but none of the providers can be installed\n  - package buildah-1.11.6-7.module+el8.2.0+5856+b8046c6d.x86_64 requires runc >= 1.0.0-26, but none of the providers can be installed\n  - package buildah-1.11.6-6.module+el8.1.1+5865+cc793d95.x86_64 requires runc >= 1.0.0-26, but none of the providers can be installed\n  - package buildah-1.11.6-4.module+el8.1.1+5259+bcdd613a.x86_64 requires runc >= 1.0.0-26, but none of the providers can be installed\n  - package buildah-1.14.9-1.module+el8.2.1+6689+748e6520.x86_64 requires runc >= 1.0.0-26, but none of the providers can be installed\n  - package buildah-1.11.6-8.module+el8.2.0+6368+cf16aa14.x86_64 requires runc >= 1.0.0-26, but none of the providers can be installed\n  - package containerd.io-1.4.3-3.1.el8.x86_64 conflicts with runc provided by runc-1.0.0-68.rc92.module+el8.3.0+8221+97165c3f.x86_64\n  - package containerd.io-1.4.3-3.1.el8.x86_64 obsoletes runc provided by runc-1.0.0-68.rc92.module+el8.3.0+8221+97165c3f.x86_64\n  - package containerd.io-1.4.3-3.1.el8.x86_64 conflicts with runc provided by runc-1.0.0-54.rc5.dev.git2abd837.module+el8+2769+577ad176.x86_64\n  - package containerd.io-1.4.3-3.1.el8.x86_64 obsoletes runc provided by runc-1.0.0-54.rc5.dev.git2abd837.module+el8+2769+577ad176.x86_64\n  - package containerd.io-1.4.3-3.1.el8.x86_64 conflicts with runc provided by runc-1.0.0-55.rc5.dev.git2abd837.module+el8.0.0+3049+59fd2bba.x86_64\n  - package containerd.io-1.4.3-3.1.el8.x86_64 obsoletes runc provided by runc-1.0.0-55.rc5.dev.git2abd837.module+el8.0.0+3049+59fd2bba.x86_64\n  - package containerd.io-1.4.3-3.1.el8.x86_64 conflicts with runc provided by runc-1.0.0-55.rc5.dev.git2abd837.module+el8.0.0.z+3525+56c076c3.x86_64\n  - package containerd.io-1.4.3-3.1.el8.x86_64 obsoletes runc provided by runc-1.0.0-55.rc5.dev.git2abd837.module+el8.0.0.z+3525+56c076c3.x86_64\n  - package containerd.io-1.4.3-3.1.el8.x86_64 conflicts with runc provided by runc-1.0.0-56.rc8.dev.git425e105.module+el8.0.0+4017+bbba319f.x86_64\n  - package containerd.io-1.4.3-3.1.el8.x86_64 obsoletes runc provided by runc-1.0.0-56.rc8.dev.git425e105.module+el8.0.0+4017+bbba319f.x86_64\n  - package containerd.io-1.4.3-3.1.el8.x86_64 conflicts with runc provided by runc-1.0.0-60.rc8.module+el8.1.0+4081+b29780af.x86_64\n  - package containerd.io-1.4.3-3.1.el8.x86_64 obsoletes runc provided by runc-1.0.0-60.rc8.module+el8.1.0+4081+b29780af.x86_64\n  - package containerd.io-1.4.3-3.1.el8.x86_64 conflicts with runc provided by runc-1.0.0-61.rc8.module+el8.1.0+4873+4a24e241.x86_64\n  - package containerd.io-1.4.3-3.1.el8.x86_64 obsoletes runc provided by runc-1.0.0-61.rc8.module+el8.1.0+4873+4a24e241.x86_64\n  - package containerd.io-1.4.3-3.1.el8.x86_64 conflicts with runc provided by runc-1.0.0-64.rc9.module+el8.1.1+5259+bcdd613a.x86_64\n  - package containerd.io-1.4.3-3.1.el8.x86_64 obsoletes runc provided by runc-1.0.0-64.rc9.module+el8.1.1+5259+bcdd613a.x86_64\n  - package containerd.io-1.4.3-3.1.el8.x86_64 conflicts with runc provided by runc-1.0.0-65.rc10.module+el8.2.0+5762+aaee29fb.x86_64\n  - package containerd.io-1.4.3-3.1.el8.x86_64 obsoletes runc provided by runc-1.0.0-65.rc10.module+el8.2.0+5762+aaee29fb.x86_64\n  - package containerd.io-1.4.3-3.1.el8.x86_64 conflicts with runc provided by runc-1.0.0-65.rc10.module+el8.2.0+6368+cf16aa14.x86_64\n  - package containerd.io-1.4.3-3.1.el8.x86_64 obsoletes runc provided by runc-1.0.0-65.rc10.module+el8.2.0+6368+cf16aa14.x86_64\n  - package containerd.io-1.4.3-3.1.el8.x86_64 conflicts with runc provided by runc-1.0.0-66.rc10.module+el8.2.1+6465+1a51e8b6.x86_64\n  - package containerd.io-1.4.3-3.1.el8.x86_64 obsoletes runc provided by runc-1.0.0-66.rc10.module+el8.2.1+6465+1a51e8b6.x86_64\n  - cannot install the best candidate for the job\n  - package runc-1.0.0-55.rc5.dev.git2abd837.module+el8+2794+c81bb0a1.x86_64 is filtered out by modular filtering\n  - package runc-1.0.0-55.rc5.dev.git2abd837.module+el8.0.0+2956+30df4692.x86_64 is filtered out by modular filtering\n  - package runc-1.0.0-55.rc5.dev.git2abd837.module+el8.0.0+4014+8662b6b2.x86_64 is filtered out by modular filtering\n  - package runc-1.0.0-55.rc5.dev.git2abd837.module+el8.1.0+3468+011f0ab0.x86_64 is filtered out by modular filtering\n  - package runc-1.0.0-56.rc5.dev.git2abd837.module+el8.1.0+4908+72a45cef.x86_64 is filtered out by modular filtering\n  - package runc-1.0.0-64.rc10.module+el8.2.0+5728+ac3aae00.x86_64 is filtered out by modular filtering\n  - package runc-1.0.0-56.rc5.dev.git2abd837.module+el8.2.0+6370+6fb6c8ca.x86_64 is filtered out by modular filtering\n  - package runc-1.0.0-64.rc10.module+el8.2.0+6369+1f4293b4.x86_64 is filtered out by modular filtering\n  - package runc-1.0.0-64.rc10.module+el8.3.0+8233+627fbb78.x86_64 is filtered out by modular filtering\n  - package runc-1.0.0-56.rc5.dev.git2abd837.module+el8.3.0+8236+8e428216.x86_64 is filtered out by modular filtering\n  - package runc-1.0.0-64.rc10.module+el8.3.0+8377+eff33c85.x86_64 is filtered out by modular filtering", "rc": 1, "results"


```

**Comment by geerlingguy** [comment]
I'm not seeing that error on the CI runs though—it seems like podman/buildah aren't in the default minimal server installs of RHEL8 or CentOS8 at this time.

**Comment by Gr4cchus** [comment]
> I'm not seeing that error on the CI runs though—it seems like podman/buildah aren't in the default minimal server installs of RHEL8 or CentOS8 at this time.

Yeah i cant comment on that, this is using something like normal/general server w/ only guest agent as additional software.

**Comment by therjmartins** [comment]
> > I'm not seeing that error on the CI runs though—it seems like podman/buildah aren't in the default minimal server installs of RHEL8 or CentOS8 at this time.
> 
> Yeah i cant comment on that, this is using something like normal/general server w/ only guest agent as additional software.


Indeed, saw the same thing when using this role today. 
Initially complained about podman -
TASK [geerlingguy.docker : Ensure containerd.io is installed.] *************************************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failures": [], "msg": "Depsolve Error occured: \n Problem: problem with installed package podman-2.0.5-5.module_el8.3.0+512+b3b58dca.x86_64\n  - package podman-2.0.5-5.module_el8.3.0+512+b3b58dca.x86_64 requires runc >= 1.0.0-57, but none of the providers can be installed\n  - package containerd.io-1.4.3-3.1.el8.x86_64 conflicts with runc provided by runc-1.0.0-68.rc92.module_el8.3.0+475+c50ce30b.x86_64\n  - package containerd.io-1.4.3-3.1.el8.x86_64 obsoletes runc provided by runc-1.0.0-68.rc92.module_el8.3.0+475+c50ce30b.x86_64\n  - cannot install the best candidate for the job\n  - package runc-1.0.0-64.rc10.module_el8.3.0+479+69e2ae26.x86_64 is filtered out by modular filtering", "rc": 1, "results": []}

Removed that and then it complained about buildah - 
TASK [geerlingguy.docker : Ensure containerd.io is installed.] *************************************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failures": [], "msg": "Depsolve Error occured: \n Problem: problem with installed package buildah-1.15.1-2.module_el8.3.0+475+c50ce30b.x86_64\n  - package buildah-1.15.1-2.module_el8.3.0+475+c50ce30b.x86_64 requires runc >= 1.0.0-26, but none of the providers can be installed\n  - package containerd.io-1.4.3-3.1.el8.x86_64 conflicts with runc provided by runc-1.0.0-68.rc92.module_el8.3.0+475+c50ce30b.x86_64\n  - package containerd.io-1.4.3-3.1.el8.x86_64 obsoletes runc provided by runc-1.0.0-68.rc92.module_el8.3.0+475+c50ce30b.x86_64\n  - cannot install the best candidate for the job\n  - package runc-1.0.0-56.rc5.dev.git2abd837.module_el8.3.0+569+1bada2e4.x86_64 is filtered out by modular filtering\n  - package runc-1.0.0-64.rc10.module_el8.3.0+479+69e2ae26.x86_64 is filtered out by modular filtering", "rc": 1, "results": []}

Removed buildah and it progressed past this. Got stuck somewhere else but thats a different problem.
