### ISSUE TITLE
Make postgres_data_dir configurable via variable

### ISSUE THREAD

**Issue by jnogol** [geerlingguy/ansible-role-awx#4]
The default AWX install configuration sets `postgres_data_dir` as /tmp/pgdocker, which is a bit annoying if you want to keep a persistant installation and try AWX for a few days (weeks, months) time. It is easy to change it if you install it from scratch, but not with this role.

**Comment by 514amir** [comment]
No offense, but this is pretty unnecessarily irresponsible. I didn't notice anywhere in the documentation where it says your install can be toast as soon as your tmp is modified.

 Anyways, my setup wasn't in production but the postgres database should definitely be moved out of the hosts tmp folder please.

I appreciate all your ansible roles. Please merge in the changes suggested by the contributor
