### ISSUE TITLE
Build issue - docker compose deprecated

### ISSUE THREAD

**Issue by jonmelia** [geerlingguy/ansible-role-awx#42]
When running this playbook on a Vagrant Ansible instance I get all the way through the playbook to here
TASK [geerlingguy.awx : Run the AWX installation playbook.] *********************************************************************************************************************************fatal: [ansible.test.com]: FAILED! => {"changed": false, "cmd": "ansible-playbook -i inventory install.yml -e postgres_data_dir=/var/lib/pgdocker", "msg": "[Errno 2] No such file or directory: b'ansible-playbook': b'ansible-playbook'", "rc": 2}

I'm using ansible-galaxy to pull the role in directly and then deploy it, so I don't keep a copy of the ansible-role-awx role locally.  I'm wondering if this is the issue

**Comment by robustq** [comment]
A few days ago, the `ansible/awx` repository deprecated the `docker-compose` installer, which this repository relied on:

https://github.com/ansible/awx/commit/af6af052d010240ed8a505e914d685bb2acb7283

**Comment by jonmelia** [comment]
Thanks for the info...  I've just started to build out from the awx git instead due to this issue

**Comment by robustq** [comment]
@jonmelia you should keep this issue open for others!

**Comment by robustq** [comment]
Also, the `docker-compose` build has moved to a slightly different configuration. Details @ 

- https://github.com/ansible/awx/blob/devel/tools/docker-compose/README.md
- https://github.com/ansible/awx/blob/devel/tools/docker-compose/docs/data_migration.md

**Comment by jonmelia** [comment]
Re-opening for information for others.

**Comment by gretel** [comment]
looks like `docker` got [replaced](https://github.com/ansible/awx/blob/devel/INSTALL.md#installing-awx) at all:

```
TASK [geerlingguy.awx : Run the AWX installation playbook.] *************************************************************************************************************************************************
fatal: [deploy01]: FAILED! => {"changed": false, "msg": "Unable to change directory before execution: [Errno 2] No such file or directory: b'/root/awx/installer'"}
```

**Comment by geerlingguy** [comment]
Yeah... I'm not sure if I'll be able to keep up with the changes. What is the best way to build AWX at this point?
