### ISSUE TITLE
Any plan to support podman instead of docker?

### ISSUE THREAD

**Issue by strus38** [geerlingguy/ansible-role-awx#43]
Hi
First, thank for all the work you are doing around ansible. Do you have any plan on rhel8 to add podman support since it is the default way to go?
If not, I may propose a PR if this is something you find useful.
Thanks

**Comment by geerlingguy** [comment]
For this role in particular, it's been difficult to keep it maintained, and now that the main way to run AWX is inside Kubernetes or OpenShift, I will be deprecating the role.
