### ISSUE TITLE
Reinstalls after machine restart

### ISSUE THREAD

**Issue by bilke** [geerlingguy/ansible-role-awx#6]
I have used this role to install awx on a VM in a cloud environment. So far installation went fine and awx itself works flawlessly, thanks a lot! But when I restart the machine it seems that it reinstalls or reconfigures awx: the machine has 100% cpu for about one hour with the the process `awx-manage celery worker ..` running. Afterwards all data is lost and awx is set back to installation defaults. I don't know if the cause of this is this role or the [awx project](https://github.com/ansible/awx) itself. Do you know how to persist data between machine restarts?

**Comment by cevich** [comment]
I recall seeing this problem while playing with OpenShift + AWX, so I don't think it's related to this role but I could be wrong (haven't looked at role yet).  Suggest searching upstream AWX issues for this, maybe there's a workaround that could be implemented in this role?

**Comment by AgentCormac** [comment]
This role stores the database in the /tmp directory. So the data will always be lost at some point.

**Comment by JulianKriel** [comment]
Specify a path outside of /tmp
Have zero issues bringing everything up after a restart, 
tested multiple times and everything is where it should be
