### ISSUE TITLE
Retain data beyond VM life

### ISSUE THREAD

**Issue by AgentCormac** [geerlingguy/ansible-role-awx#9]
As alluded to in previous issues:
-[Reinstalls after machine restart](https://github.com/geerlingguy/ansible-role-awx/issues/6)
-[Make postgres_data_dir configurable via variable](https://github.com/geerlingguy/ansible-role-awx/issues/4)

This role does not allow you to retain AMX data and configuration. Need to be able to retain data beyond the life of the VM. Using Ansible is all about slash and burn environments, build and env, inject data etc.

This is especially an issue when running AWX with Vagrant and VirtualBox. I would like to be able to map the DB directory to a share on the host and for the (host resident) DB not to be wiped when the VM is recreated.

OR

How do I extract data and then re-inject it when the VM is rebuilt?

The backup.yml and restore.yml file mentioned in the Tower documentation do not seem to exist.
Copying the DB files seems to corrupt the DB (suspect key/certificate issue).
 Changing the DB location as Pull Request #4 postgres_data_dir in a variable retains data during reboots but overwrites the data on rebuild.

Is anyone maintaining this role? It doesnt look like it has been updated in a while.

**Comment by vab2048** [comment]
Did you manage to find a solution to the fact that "the backup.yml and restore.yml file mentioned in the Tower documentation" do not actually exist?
